### ISSUE TITLE
Can't add subscriber.

### ISSUE THREAD

**Issue by ghost** [lfidnl/ptilinopus#2]
Hi!

I sent post request to add subscriber like example code.

``` ruby
api = Primary::API.new("api_key")
api.call(:post, "subscribers", {email: 'test_email@test.com', id: 123456})
```

But, response code is 404.
I read [mailerlite api docs](http://docs.mailerlite.com/pages/subscribers#post), and maybe we need `list_id` in request path.

ptilinopus make request path just `https://app.mailerlite.com/api/v1/#{method}/` .

``` ruby
response = self.class.send(type, API_PATH + method, body: params, headers: DEFAULT_HEADER, query_string_normalizer: query_string_normalizer)
```

I think we should include `list_id` in request path.
I was really grad if you fix it ^^b

thanks!

**Comment by ghost** [comment]
I found way to add subscriber like this,

``` ruby
api.call(:post, "subscribers/123456", {email: "someone@email.com"})
```

**Comment by lfidnl** [comment]
Hi. Thanks for comment!

I think they changed way to processing requests, because my code of old project stops working too.
I'll fix this problem:
if request have _id_ param, then it should be appended to method path.

**Comment by lfidnl** [comment]
Hmmm... Appending id param to method path is not a good idea, because there is not way to use _/subscribers/{list_id}/import_ method. So the best way is to use your "workaround"
So I'll update the README file

**Comment by ghost** [comment]
@lfidnl 
OK! Thanks!
