### ISSUE TITLE
Using the subscribers/list_id/import endpoint?

### ISSUE THREAD

**Issue by nlsrchtr** [lfidnl/ptilinopus#3]
Is there a working example on how to use the `subscribers/list_id/import` with multiple subscribers and custom fields?

Thanks for your help.

**Comment by lfidnl** [comment]
Hello.

Now, there is no way to use `subscribers/list_id/import` method. I check that Mailerlite API wroks great with `Content-Type: application/json` header and converted params to json. So I can fix it today/tomorrow.

Please, can you test it with following changes:

``` ruby
# lib/ptilinopus.rb:8
DEFAULT_HEADER = {"Content-Type" => "application/json"}

# lib/ptilinopus.rb:22
response = self.class.send(type, API_PATH + method, body: params.to_json, headers: DEFAULT_HEADER)
```

Sorry, but now I doesn't use this gem and I can't fully test all API. So, please, give me feedback and everythis will be great I'll push this changes to github, or you can create Pull request :)

**Comment by lfidnl** [comment]
Working example:

``` ruby
subscribers = [
    {email: 'test_email@test1s.com', name: 'Test user'},
    {email: 'another_test_email@test1s.com', name: 'Another Test user'}
]
Ptilinopus::API.call(:post, "subscribers/123456/import", {subscribers: subscribers})
```

Please, update gem.

**Comment by ghost** [comment]
:+1:
